name: Deploy Spring Boot Backend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest master with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Copy keystore into resources before build
        run: |
          cp /home/student/apps/backend/Findigo/src/main/resources/keystore.jks src/main/resources/
        working-directory: /home/student/actions-runner/_work/Findigo/Findigo

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: /home/student/actions-runner/_work/Findigo/Findigo

      - name: Copy JAR to app directory
        if: github.event_name == 'push'
        run: cp target/*.jar /home/student/apps/backend/Findigo/target/
        working-directory: /home/student/actions-runner/_work/Findigo/Findigo

      - name: Restart backend service
        if: github.event_name == 'push'
        run: |
          sudo systemctl restart backend
